name: latest-test
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - "*.md"
      - "*-deploy.yaml"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: [6]
        os: [ ubuntu-20.04 ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura Linguard
        #run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Threshold=80 Linguard

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2.1.0
        if: always()

      - name: Check docs are compiled successfully
        run: |
          cd docs && make html && cd ..