name: stable-deploy
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*-test.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: [6]
        os: [ ubuntu-20.04 ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build and publish
        run: |
          dotnet publish -c Release -o ./dist/docker/cli/ ./Linguard/Cli
          dotnet publish -c Release -o ./dist/docker/web/ ./Linguard/Web
          dotnet publish -c Release -o ./dist/linux/linguard-web/ --sc --os linux .\Linguard\Web
          dotnet publish -c Release -o ./dist/linux/linguard-cli/ --sc --os linux .\Linguard\Cli
          tar -zcf linguard-docker.tar.gz ./dist/docker/
          tar -zcf linguard-linux.tar.gz ./dist/linux/ 
          cp scripts/* dist/
          cp -r systemd/ dist/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stable, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: "linux/amd64, linux/arm64"
          push: true

      - name: Create GH release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.get_version.outputs.version }}
          tag: "v${{ steps.get_version.outputs.version }}"
          commit: "main"
          artifacts: "dist/linguard-linux.tar.gz"
          bodyFile: "release-notes.md"
          discussionCategory: "Announcements"
          token: ${{ secrets.GITHUB_TOKEN }}